apiVersion: apps/v1
kind: Deployment
metadata:
  name: linio-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linio-challenge
  template:
    metadata:
      labels:
        app: linio-challenge
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: linio-challenge
        image: registry.cloud.okteto.net/mauriciovalli/linio-challenge:dev
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        env:
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: linio-challenge
data:
  application.yml: |-
    spring:
     cloud:
      kubernetes:
        discovery:
          all-namespaces: false
          service-labels:
            spring-boot: true
---
apiVersion: v1
kind: Service
metadata:
  name: linio-challenge
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: linio-challenge
